# <font color = #14f72e>MATHEMATICAL OPERATIONS:

     

In [2]:
import numpy as np

In [3]:
a=np.array ([30,65,55,79,25])
b=np.array ([4,8,5,9,2])
print(a)
print(b)


[30 65 55 79 25]
[4 8 5 9 2]


In [4]:
np.add(a,b)

array([34, 73, 60, 88, 27])

In [5]:
c=np.array ([4,8,52])
print(c)

[ 4  8 52]


In [6]:
np.add(a,c)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [7]:
# The oerands should have same dimension and size in order to add

In [9]:
np.subtract(a,b)

array([26, 57, 50, 70, 23])

In [10]:
np.multiply(a,b)

array([120, 520, 275, 711,  50])

In [11]:
np.divide(a,b)

array([ 7.5       ,  8.125     , 11.        ,  8.77777778, 12.5       ])

In [15]:
np.floor_divide(a,b)#floor division

array([ 7,  8, 11,  8, 12])

In [16]:
np.mod(a,b)# returns remainder

array([2, 1, 0, 7, 1])

In [18]:
np.divmod(a,b)# gives floor division value + remainder values deta hai

(array([ 7,  8, 11,  8, 12]), array([2, 1, 0, 7, 1]))

In [20]:
np.log(a)# if base isnt mentioned then its base e

array([3.40119738, 4.17438727, 4.00733319, 4.36944785, 3.21887582])

In [21]:
np.log10(b)# gives log values with base 10

array([0.60205999, 0.90308999, 0.69897   , 0.95424251, 0.30103   ])

In [23]:
print(a)
np.sqrt(a)

[30 65 55 79 25]


array([5.47722558, 8.06225775, 7.41619849, 8.88819442, 5.        ])

In [24]:
print(a)
np.power(a,8)

[30 65 55 79 25]


array([-1029996288,  1189200385,  -744512191,  1806907777, -2030932031],
      dtype=int32)

In [28]:
print(a)
np.power(a,3)

[30 65 55 79 25]


array([ 27000, 274625, 166375, 493039,  15625], dtype=int32)

In [25]:
print(a)
np.power(a,b)

[30 65 55 79 25]


array([    810000, 1189200385,  503284375, 1011793615,        625])

In [26]:
np.sin(a)

array([-0.98803162,  0.82682868, -0.99975517, -0.44411267, -0.13235175])

In [27]:
np.cos(a)

array([ 0.15425145, -0.56245385,  0.02212676, -0.89597095,  0.99120281])

In [34]:
np.tan(a)

array([ -6.4053312 ,  -1.47003826, -45.18308791,   0.49567753,
        -0.13352641])

In [30]:
1/np.tan(a)#cot(a) is non executable hence we use 1/tan()

array([-0.15611995, -0.6802544 , -0.02213217,  2.01744064, -7.48915531])

In [35]:
1/np.sin(a)#cosec()

array([-1.01211335,  1.20944039, -1.00024489, -2.25168087, -7.55562355])

In [36]:
1/np.cos(a)#sec()

array([ 6.48292123, -1.77792364, 45.19415264, -1.11610762,  1.00887527])

## <font color=#f7ec14>STATISTICAL FUNCTION:

In [37]:
a

array([30, 65, 55, 79, 25])

In [46]:
# min, max ,median , mean, st deviation, varience

In [39]:
np.max(a)

79

In [40]:
np.min(a)

25

In [41]:
np.mean(a)

50.8

In [42]:
np.median(a)

55.0

In [53]:
#  MODE = 3(MEDIAN)-2(MEAN)
np.mode(a)# mode cant be calculated

AttributeError: module 'numpy' has no attribute 'mode'

In [47]:
np.std(a)#root(varience)

20.556264252047356

In [45]:
np.var(a)

422.56000000000006

In [48]:
#cumsum-cumulative summation
b

array([4, 8, 5, 9, 2])

In [49]:
np.cumsum(b)

array([ 4, 12, 17, 26, 28])

In [52]:
#repeat
a=np.array([1,2,3,4])
np.repeat(a,4)#each element is repeated 4 tyms

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [55]:
#tile
a=np.array([1,2,3,4])
np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [58]:
#where
a=np.array([1,2,4,5,4,6,4,4,7,4])
np.where(a==4)#gives all the index posn where it finds 4

(array([2, 4, 6, 7, 9], dtype=int64),)

In [59]:
a=np.array([30,58,67,40,99,87,34])
a

array([30, 58, 67, 40, 99, 87, 34])

In [60]:
#argmax= array ka max value ka index posn
np.argmax(a)

4

In [62]:
#argmin= array a min value ka index posn
np.argmin(a)

0

## VECTOR MATHS

In [65]:
#Vector maths
a=np.array([[1,3],[2,4]])
b=np.array([[5,7],[9,8]])
print(a)
print(b)

[[1 3]
 [2 4]]
[[5 7]
 [9 8]]


In [67]:
np.dot(a,b)

array([[32, 31],
       [46, 46]])

In [68]:
np.cross(a,b)

array([ -8, -20])

![MyImage](cp1.jpg)

![MyImage](cp2.jpg)

![MyImage](cp.4.jpg)

In [69]:
#transpose
np.transpose(a)

array([[1, 2],
       [3, 4]])

In [70]:
a.T

array([[1, 2],
       [3, 4]])

 ### Indexing & slicing in 1-D array

In [71]:
 #Indexing & slicing in 1-D array
a= np.array([20,60,79,45,88,4])
a

array([20, 60, 79, 45, 88,  4])

#### Indexing

In [74]:
a[2]

79

In [75]:
a[-3]

45

#### Slicing:

In [76]:
print(a)
a[1::2]

[20 60 79 45 88  4]


array([60, 45,  4])

In [77]:
#reverse
a[::-1]

array([ 4, 88, 45, 79, 60, 20])

### Indexing & slicing in 2-D array

In [79]:
b=np.random.randint(1,20,(5,5))
b

array([[ 1,  2,  6,  7, 13],
       [ 6, 13, 17,  2, 19],
       [10,  7,  9, 16,  6],
       [ 7, 14, 11, 14, 19],
       [10,  1, 11,  5, 13]])

#### Indexing:

In [84]:
b[2,3] # [row index , coln index]

16

In [85]:
b[2][3]

16

In [86]:
b[-1][2]

11

In [94]:
# There matrix posn are from 0 index i.e a[0,0], a[0,1],.....so on

In [95]:
#Indexing:
# syntax: var[row-index,column_index]✅
print(b)
b[3,2]

[[ 1  2  6  7 13]
 [ 6 13 17  2 19]
 [10  7  9 16  6]
 [ 7 14 11 14 19]
 [10  1 11  5 13]]


11

#### Slicing:

**row slicing**= [start:stop+1:step]
**column slicing**=[start:stop+1:step]


**Syntax:** var[row_slicing,column_slicing]

In [98]:
print(b)
b[1:4:1,1:4:1]

[[ 1  2  6  7 13]
 [ 6 13 17  2 19]
 [10  7  9 16  6]
 [ 7 14 11 14 19]
 [10  1 11  5 13]]


array([[13, 17,  2],
       [ 7,  9, 16],
       [14, 11, 14]])

In [99]:
print(b)
b[::2,1:4:1]

[[ 1  2  6  7 13]
 [ 6 13 17  2 19]
 [10  7  9 16  6]
 [ 7 14 11 14 19]
 [10  1 11  5 13]]


array([[ 2,  6,  7],
       [ 7,  9, 16],
       [ 1, 11,  5]])

In [100]:
b[1::2,1::2]

array([[13,  2],
       [14, 14]])

In [90]:
b[2,::]
#prints row at index 2

array([10,  7,  9, 16,  6])

In [91]:
b[::,1] #prints column at index 1

array([ 2, 13,  7, 14,  1])

In [92]:
b[:3:2,2:4:1]

array([[ 6,  7],
       [ 9, 16]])

In [93]:
# row starts from beginning , goes till the 3rd row and the step is 2
# column starts from 2nd column , till 4 as it stops at 3rd column

In [96]:
b[3] # bydefault row
# jo index posn doge by default row lega us row ke sare elements print krdega 

array([ 7, 14, 11, 14, 19])

In [97]:
# to print column
b[::,1]

array([ 2, 13,  7, 14,  1])

### CONCATENATION: Joining 2 Matrices

![MyImage](c1.jpg)

In [103]:
a=np.random.randint(1,20,(2,2))
a

array([[10,  5],
       [14, 18]])

In [104]:
b=np.random.randint(1,20,(2,4))
b

array([[ 3, 14,  4, 18],
       [15,  4, 12, 15]])

In [105]:
c=np.random.randint(1,20,(4,4))
c

array([[ 6,  8,  4,  6],
       [ 5,  3,  6,  9],
       [ 7,  7, 14, 10],
       [ 2, 18, 14,  9]])

![MyImage](c2.jpg)

In [107]:
np.concatenate((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [108]:
np.concatenate((a,b),axis = 1)

array([[10,  5,  3, 14,  4, 18],
       [14, 18, 15,  4, 12, 15]])

In [109]:
np.concatenate((b,c))

array([[ 3, 14,  4, 18],
       [15,  4, 12, 15],
       [ 6,  8,  4,  6],
       [ 5,  3,  6,  9],
       [ 7,  7, 14, 10],
       [ 2, 18, 14,  9]])

# STACK:

> hstack: horizontal stacking
> 
> vstack: vertical stacking

![MyImage](c3.jpg)

In [110]:
np.hstack((a,b))

array([[10,  5,  3, 14,  4, 18],
       [14, 18, 15,  4, 12, 15]])

In [111]:
np.vstack((b,c))

array([[ 3, 14,  4, 18],
       [15,  4, 12, 15],
       [ 6,  8,  4,  6],
       [ 5,  3,  6,  9],
       [ 7,  7, 14, 10],
       [ 2, 18, 14,  9]])

---

# <font color=#3af714> PANDAS: 🐼

    Pandas is an open-source python library designed for data manipulation and analysis . It provides powerful and flexible data structures , in the formof Series and Data Frame .

Data id of 2 types:
>**1.Series**: Single column only
>
>**2.DataFrame:** Consists of many / multiple columns

In [113]:
import pandas as pd
import numpy as np

In [115]:
# Creating a series:
# pd.Series converts sequential data into series
s= pd.Series(['a','b','d','f','e'])
s

0    a
1    b
2    d
3    f
4    e
dtype: object

In [116]:
# here the 2nd column is for index position

In [117]:
# we can change the index no. according to our need :
# to update index we have to pass the series into index
s= pd.Series(['a','b','d','f','e'],index=[10,20,30,40,50])
s

10    a
20    b
30    d
40    f
50    e
dtype: object

In [120]:
s[3] # error dega as index values change krdiya hai humne

KeyError: 3

In [119]:
s[30]

'd'

In [123]:
s[1:3:1] # while slicing weuse index values as in relity its not completely chnged , its just changed for showcasing the index values 
# We can also perform slicing using the updated index values

20    b
30    d
dtype: object

#### TUPLE to SERIES:


In [124]:
t= pd.Series((10,20,30,50,90))
t

0    10
1    20
2    30
3    50
4    90
dtype: int64

In [125]:
t[1:3:1]

1    20
2    30
dtype: int64

In [127]:
s[1:4:1] # Series

20    b
30    d
40    f
dtype: object

#### ARRAY to SERIES

Array ke lie numpy chie jo pehele add krdiya tha

In [128]:
a=np.array([20,30,38,90,80,18])
s=pd.Series(a)
a

array([20, 30, 38, 90, 80, 18])

In [129]:
s

0    20
1    30
2    38
3    90
4    80
5    18
dtype: int32

### SET to SERIES:

In [130]:
a=pd.Series({10,20,40,50,80})
a

TypeError: 'set' type is unordered

In [131]:
# AS set is unordered it shows error

#### DICTIONARY to SERIES:

    Dictionary ka key uske index mei likha jata hai aur uska value series ke value mei set hojata hai

In [133]:
d=pd.Series({'a':1,'b':2,'c':3,'d':4})
d

a    1
b    2
c    3
d    4
dtype: int64

In [134]:
d1=pd.Series({'a':1,'b':2,'c':3,'d':4},index=['e','a','f','b'])
d1

e    NaN
a    1.0
f    NaN
b    2.0
dtype: float64

    jo key ka value define nhi kiya tha waha NaN aya 

    NaN : Not A NUMBER


##### _INDEXING :_

In [135]:
d1['f']

nan

In [136]:
d1['a']

1.0

In [137]:
d1['b']

2.0

In [138]:
d['a']

1

In [139]:
d[2]

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10824\464593666.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  d[2]


3

In [140]:
print(d)

a    1
b    2
c    3
d    4
dtype: int64


##### _SLICING:_

In [141]:
d[1:5:2]

b    2
d    4
dtype: int64

In [142]:
d['b':'d':2]

b    2
d    4
dtype: int64

## DATA FRAME

In [158]:
d= {'Name':['Vishnu','Ram','Sita','Gita','Hari','Krishna','Radhe'],'Roll':[21,22,23,24,25,26,27],'Age':[23,21,25,24,23,19,20],'Marks':['🎶','🙌','✅','🙊','❤️','🤩','🙈']}

In [159]:
d

{'Name': ['Vishnu', 'Ram', 'Sita', 'Gita', 'Hari', 'Krishna', 'Radhe'],
 'Roll': [21, 22, 23, 24, 25, 26, 27],
 'Age': [23, 21, 25, 24, 23, 19, 20],
 'Marks': ['🎶', '🙌', '✅', '🙊', '❤️', '🤩', '🙈']}

In [160]:
type(d)

dict

#### Dictionary to DataFrame:

In [161]:
s=pd.DataFrame(d)
s

Name  Roll  Age Marks
0   Vishnu    21   23     🎶
1      Ram    22   21     🙌
2     Sita    23   25     ✅
3     Gita    24   24     🙊
4     Hari    25   23    ❤️
5  Krishna    26   19     🤩
6    Radhe    27   20     🙈

In [162]:
type(s)

pandas.core.frame.DataFrame