# <font color=#30fc03>NumPy: NUMERICAL PYTHON:

    NumPy is a Python library which is used to perform different mathematical operations on arrays.
    Array is denoted with '[]' . 
    
    Its:
- ordered (index position is fixed)
- mutable (items can be modified) 
- homogenous (items of similar datatype ) collection of items.

In [1]:
import numpy as np

In [2]:
# Creating 1-D Array:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
type(a) # ndarray : n-dimensional array

numpy.ndarray

In [7]:
b= np.array([20,40,'cat',3.5,True])
b# string bana diya sara data type : so ek naya data type name diya gya temporarily i.e '<U32'

array(['20', '40', 'cat', '3.5', 'True'], dtype='<U32')

In [8]:
type(b)

numpy.ndarray

In [12]:
b=np.array([20,40,3.5,True])
b
# all datatypes converted to float
#True in numeric can be 1 as ) is False
#20. , 40. , is generated from int values 20 nd 40

array([20. , 40. ,  3.5,  1. ])

In [13]:
type(b)

numpy.ndarray

**- This implies that all datat types are homogenous.**

**- STRING>FLOAT>INTEGER-- its the priority.**

In [14]:
# Tuple to Array:
t= np.array((1,2,3,4,4))
t

array([1, 2, 3, 4, 4])

In [15]:
#set to array:
s=np.array({1,2,3,4,4})
s

array({1, 2, 3, 4}, dtype=object)

In [16]:
#there assigned datatype is object (neither its a string nor any other primitive datatype)
# Set is unordered and hence it cannot be properly converted to a numpy array

In [18]:
# Dictionary to array
d=np.array({'a':1,'b':2,'c':3})
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [19]:
#each element is assigned as object datatype as its neither a string nor a float or integer

In [20]:
# Creating a 2-D Array:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
#[...] implies one dimension
#1-D Array:a= np.array([[1,2,3])
# 2-D Array:a= np.array([[1,2,3],[4,5,6]]])

In [22]:
a= np.array([[1,2,3],{4,5,6}])
a
# becoz 2nd 1 is set so it shows error

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [23]:
b= np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# ARRAY ATTRIBUTES

In [25]:
b.shape
#shows dimensions: that is (row,column)

(3, 3)

In [26]:
b.size#to check total no. of elements in an array

9

In [27]:
b.ndim
#To chechk the no. of dimensions of the array

2

In [38]:
# Arrange - returns a 1-D array of the givem range / sequence 
# only 1 - d can be arranged 
np.arange(1,8)


array([1, 2, 3, 4, 5, 6, 7])

In [35]:

np.arange(1,8,2)

array([1, 3, 5, 7])

In [39]:
np.zeros(5) # null array / null matrix is created

array([0., 0., 0., 0., 0.])

In [45]:
np.zeros((3,5))
# 2-d = 2 brackets are used

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
# Creating a 3-d array
d=np.array([[[1,2,3,4],[1,11,111,1111]],[[2,7,8,9],[0,8,6,5]]])
d

array([[[   1,    2,    3,    4],
        [   1,   11,  111, 1111]],

       [[   2,    7,    8,    9],
        [   0,    8,    6,    5]]])

In [51]:
d.shape

(2, 2, 4)

In [52]:
d.size

16

In [53]:
d.ndim

3

In [56]:
d.arange(1,15)# done only for 1d array

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [42]:
# use shift+ tab to get details

#### ZEROS: used to creat null mtrix

In [43]:
np.zeros((5,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [44]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [59]:
np.zeros((5,5)).astype('int') # koi ek data type hai jisse diff mei chnge krna hai 
#toh hum astype deke wo datatpe likhdenge toh matrix mei data wese represent hoga

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### ONES : 1 represent karega matrix mei 

In [60]:
np.ones(4)

array([1., 1., 1., 1.])

In [61]:
np.ones((9,9),int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [62]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [64]:
np.ones((8,5)).astype('str')

array([['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0'],
       ['1.0', '1.0', '1.0', '1.0', '1.0']], dtype='<U32')

In [69]:
np.ones((8,5)).astype('bool')

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [67]:
np.ones((9,9))*3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.]])

#### FULL: to fill up the given no. in entire matrix

In [65]:
np.full((5,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [70]:
np.full((5,5),"❤️")# emoji ka dt nhi hota toh usko ek variable dt dedia U2

array([['❤️', '❤️', '❤️', '❤️', '❤️'],
       ['❤️', '❤️', '❤️', '❤️', '❤️'],
       ['❤️', '❤️', '❤️', '❤️', '❤️'],
       ['❤️', '❤️', '❤️', '❤️', '❤️'],
       ['❤️', '❤️', '❤️', '❤️', '❤️']], dtype='<U2')

#### EYE : Identity matrix solve ho sakta hai 
#### Diagonal matrix  is always a square matrix 

In [72]:
#eye
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### LINSPACE: Linearly arranged spaces 

       st aur end ke beech ko ese divide krna hai ki given values equally separate krde

In [73]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [74]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [75]:
np.linspace(1,40,12)

array([ 1.        ,  4.54545455,  8.09090909, 11.63636364, 15.18181818,
       18.72727273, 22.27272727, 25.81818182, 29.36363636, 32.90909091,
       36.45454545, 40.        ])

#### RANDOM NUMBERS: random.rand() -> used to generate random data between 0 & 1

In [76]:
np.random.rand()

0.38659403093853906

In [77]:
np.random.rand(5)

array([0.06242835, 0.93728954, 0.60912831, 0.15301843, 0.19635653])

In [78]:
np.random.rand(3,4)

array([[0.45250332, 0.23797881, 0.12591868, 0.26657492],
       [0.47173513, 0.32557472, 0.94878529, 0.45845207],
       [0.51213115, 0.12322786, 0.81592471, 0.54889339]])

In [79]:
#2-D array is made matrix size is 3X4

In [80]:
np.random.rand(3,4)*100

array([[77.20803254,  3.56920683, 11.90302855, 71.38425501],
       [61.15370014, 62.02109835, 63.5569743 , 67.37396468],
       [75.20060604, 10.86154271, 33.05029253, 37.2823982 ]])

In [81]:
#generates random value giving values greater than the decimal range

In [82]:
#matrix ke har element mei 100 multiply hogya

In [87]:
np.random.randint(3,5317) # gives random int betn 3 to 5317

1904

In [88]:
np.random.randint(10,40,(4,3))

array([[21, 33, 12],
       [16, 36, 11],
       [21, 21, 14],
       [30, 21, 15]])